
import type IValidationResult from '../models/validation/ValidationResult';
import type { IValidator } from '../models/validation/Validator';
import * as rules from './Rules';

export class Validator implements IValidator {
    // Rulesets can be added for future kernel versions, if different validation is needed
    ruleset: "UTDefect" = "UTDefect";

    // TODO: Add weld parameter validation
    rules: Record<string, (value: string | number | boolean) => IValidationResult> = {
        'MethodMaterialMetalPropertiesLongitudinalVelocity': rules.default.MethodMaterialMetalPropertiesLongitudinalVelocity,
        'MethodMaterialMetalPropertiesTransversalVelocity': rules.default.MethodMaterialMetalPropertiesTransversalVelocity,
        'MethodMaterialMetalPropertiesDamping': rules.default.MethodMaterialMetalPropertiesDamping,
        'MethodMaterialConstantsC11': rules.default.MethodMaterialConstantsC11,
        'MethodMaterialConstantsC22': rules.default.MethodMaterialConstantsC22,
        'MethodMaterialConstantsC33': rules.default.MethodMaterialConstantsC33,
        'MethodMaterialConstantsC12': rules.default.MethodMaterialConstantsC12,
        'MethodMaterialConstantsC13': rules.default.MethodMaterialConstantsC13,
        'MethodMaterialConstantsC23': rules.default.MethodMaterialConstantsC23,
        'MethodMaterialConstantsC44': rules.default.MethodMaterialConstantsC44,
        'MethodMaterialConstantsC55': rules.default.MethodMaterialConstantsC55,
        'MethodMaterialConstantsC66': rules.default.MethodMaterialConstantsC66,
        'MethodMaterialEulersPhi': rules.default.MethodMaterialEulersPhi,
        'MethodMaterialEulersTheta': rules.default.MethodMaterialEulersTheta,
        'MethodMaterialEulersPsi': rules.default.MethodMaterialEulersPsi,
        'MethodUTTechniqueProbeType': rules.default.MethodUTTechniqueProbeType,
        'MethodUTTechniqueTransmitter': rules.default.MethodUTTechniqueTransmitter,
        'MethodUTTechniqueReceiver': rules.default.MethodUTTechniqueReceiver,
        'MethodCalibrationType': rules.default.MethodCalibrationType,
        'MethodCalibrationDepth': rules.default.MethodCalibrationDepth,
        'MethodCalibrationDiameter': rules.default.MethodCalibrationDiameter,
        'MethodMeshSizeXStart': rules.default.MethodMeshSize,
        'MethodMeshSizeXEnd': rules.default.MethodMeshSize,
        'MethodMeshSizeXIncrement': rules.default.MethodMeshSizeXIncrement,
        'MethodMeshSizeYStart': rules.default.MethodMeshSize,
        'MethodMeshSizeYEnd': rules.default.MethodMeshSize,
        'MethodMeshSizeYIncrement': rules.default.MethodMeshSizeYIncrement,
        'MethodMeshWeldType': rules.default.MethodMeshWeldType,
        'MethodMeshWeldParametersInputEnergy': rules.default.MethodMeshWeldParametersInputEnergy,
        'MethodMeshWeldParametersInitialTemperature': rules.default.MethodMeshWeldParametersInitialTemperature,
        'MethodMeshWeldParametersHeatEfficiency': rules.default.MethodMeshWeldParametersHeatEfficiency,
        'MethodMeshWeldGeometryB1': rules.default.MethodMeshWeldGeometryB1,
        'MethodMeshWeldGeometryB2': rules.default.MethodMeshWeldGeometryB2,
        'MethodMeshWeldGeometryB3': rules.default.MethodMeshWeldGeometryB3,
        'MethodMeshWeldGeometryT1': rules.default.MethodMeshWeldGeometryT1,
        'MethodMeshWeldGeometryT2': rules.default.MethodMeshWeldGeometryT2,
        'MethodMeshWeldPropertiesSpecificHeat': rules.default.MethodMeshWeldPropertiesSpecificHeat,
        'MethodMeshWeldPropertiesInitialGrainSize': rules.default.MethodMeshWeldPropertiesInitialGrainSize,
        'MethodMeshWeldPropertiesDensity': rules.default.MethodMeshWeldPropertiesDensity,
        'MethodMeshWeldPropertiesMeltingTemperature': rules.default.MethodMeshWeldPropertiesMeltingTemperature,
        'MethodMeshWeldPropertiesTemperatureDiffusivity': rules.default.MethodMeshWeldPropertiesTemperatureDiffusivity,
        'MethodMeshWeldPropertiesActivationEnergy': rules.default.MethodMeshWeldPropertiesActivationEnergy,
        'MethodMeshWeldPropertiesExponentialGrowthConstant': rules.default.MethodMeshWeldPropertiesExponentialGrowthConstant,
        'MethodMeshWeldPropertiesGrainBoundaryEnergyConstant': rules.default.MethodMeshWeldPropertiesGrainBoundaryEnergyConstant,
        'MethodMeshWeldControlVolumeXStart': rules.default.MethodMeshWeldControlVolumeXStart,
        'MethodMeshWeldControlVolumeXEnd': rules.default.MethodMeshWeldControlVolumeXEnd,
        'MethodMeshWeldControlVolumeYStart': rules.default.MethodMeshWeldControlVolumeYStart,
        'MethodMeshWeldControlVolumeYEnd': rules.default.MethodMeshWeldControlVolumeYEnd,
        'MethodMeshWeldControlVolumeDepth': rules.default.MethodMeshWeldControlVolumeDepth,
        'MethodMeshWeldControlVolumeThickness': rules.default.MethodMeshWeldControlVolumeThickness,
        'MethodMeshWeldControlVolumeGrainSize': rules.default.MethodMeshWeldControlVolumeGrainSize,
        'MethodMeshWeldControlVolumeInitial': rules.default.MethodMeshWeldControlVolumeInitial,
        'MethodMeshWeldSNRatioofSDH': rules.default.MethodMeshWeldSNRatioPercentOfSDH,
        'MethodMeshWeldSNRatioDiameter': rules.default.MethodMeshWeldSNRatioDiameter,
        'MethodMeshWeldSNRatioDepth': rules.default.MethodMeshWeldSNRatioDepth,
        'MethodTimeWindowType': rules.default.MethodTimeWindowType,
        'MethodTimeWindowStart': rules.default.MethodTimeWindowStart,
        'MethodTimeWindowEnd': rules.default.MethodTimeWindowEnd,
        'MethodTimeWindowIncrement': rules.default.MethodTimeWindowIncrement,
        'MethodTimeWindowDepth': rules.default.MethodTimeWindowDepth,
        'MethodTimeWindowX': rules.default.MethodTimeWindowX,
        'MethodTimeWindowY': rules.default.MethodTimeWindowY,
        'TransmitterShapeandElementsType': rules.default.TransmitterShapeAndElementsType,
        'TransmitterShapeandElementsAutoNumElements': rules.default.TransmitterShapeAndElementsAutoNumElements,
        'TransmitterShapeandElementsXLength': rules.default.TransmitterShapeAndElementsXLength,
        'TransmitterShapeandElementsXElements': rules.default.TransmitterShapeAndElementsXElements,
        'TransmitterShapeandElementsXGap': rules.default.TransmitterShapeAndElementsXGap,
        'TransmitterShapeandElementsYLength': rules.default.TransmitterShapeAndElementsYLength,
        'TransmitterShapeandElementsYElements': rules.default.TransmitterShapeAndElementsYElements,
        'TransmitterShapeandElementsYGap': rules.default.TransmitterShapeAndElementsYGap,
        'TransmitterSpectrumFrequency': rules.default.TransmitterSpectrumFrequency,
        'TransmitterSpectrumBandwidth': rules.default.TransmitterSpectrumBandwidth,
        'TransmitterSpectrumInputF1': rules.default.TransmitterSpectrumInputF1,
        'TransmitterSpectrumInputF2': rules.default.TransmitterSpectrumInputF2,
        'TransmitterSpectrumInputF3': rules.default.TransmitterSpectrumInputF3,
        'TransmitterSpectrumInputF4': rules.default.TransmitterSpectrumInputF4,
        'TransmitterSpectrumInputHeightatF2AF': rules.default.TransmitterSpectrumInputHeightatF2AF,
        'TransmitterSpectrumInputHeightatF3BF': rules.default.TransmitterSpectrumInputHeightatF3BF,
        'TransmitterFocusFocalDistance': rules.default.TransmitterFocusFocalDistance,
        'TransmitterPositionX': rules.default.TransmitterPositionX,
        'TransmitterPositionY': rules.default.TransmitterPositionY,
        'TransmitterWaveType': rules.default.TransmitterWaveType,
        'TransmitterWaveSuppression': rules.default.TransmitterWaveSuppression,
        'TransmitterBeamAnglesAngle': rules.default.TransmitterBeamAnglesAngle,
        'TransmitterBeamAnglesSkewAngle': rules.default.TransmitterBeamAnglesSkewAngle,
        'TransmitterWedgeLongitudinalWavespeed': rules.default.TransmitterWedgeLongitudinalWavespeed,
        'TransmitterWedgeTransversalWavespeed': rules.default.TransmitterWedgeTransversalWavespeed,
        'TransmitterWedgeDensity': rules.default.TransmitterWedgeDensity,
        'TransmitterWedgeAngle': rules.default.TransmitterWedgeAngle,
        'TransmitterWedgeWidth': rules.default.TransmitterWedgeWidth,
        'TransmitterEulerAnglesPhi': rules.default.TransmitterEulerAnglesPhi,
        'TransmitterEulerAnglesTheta': rules.default.TransmitterEulerAnglesTheta,
        'TransmitterEulerAnglesPsi': rules.default.TransmitterEulerAnglesPsi,
        'TransmitterFluidSpecificationDensityRatio': rules.default.TransmitterFluidSpecificationDensityRatio,
        'TransmitterFluidSpecificationFluidWavespeed': rules.default.TransmitterFluidSpecificationFluidWavespeed,
        'TransmitterFluidSpecificationDamping': rules.default.TransmitterFluidSpecificationDamping,
        'TransmitterCouplant': rules.default.TransmitterCouplant,
        'TransmitterDistanceProbeSurface': rules.default.TransmitterDistanceProbeSurface,
        'ReceiverShapeandElementsType': rules.default.ReceiverShapeAndElementsType,
        'ReceiverShapeandElementsAutoNumElements': rules.default.ReceiverShapeAndElementsAutoNumElements,
        'ReceiverShapeandElementsXLength': rules.default.ReceiverShapeAndElementsXLength,
        'ReceiverShapeandElementsXElements': rules.default.ReceiverShapeAndElementsXElements,
        'ReceiverShapeandElementsXGap': rules.default.ReceiverShapeAndElementsXGap,
        'ReceiverShapeandElementsYLength': rules.default.ReceiverShapeAndElementsYLength,
        'ReceiverShapeandElementsYElements': rules.default.ReceiverShapeAndElementsYElements,
        'ReceiverShapeandElementsYGap': rules.default.ReceiverShapeAndElementsYGap,
        'ReceiverFocusType': rules.default.ReceiverFocusType,
        'ReceiverFocusFocalDistance': rules.default.ReceiverFocusFocalDistance,
        'ReceiverSeparationX': rules.default.ReceiverSeparationX,
        'ReceiverSeparationY': rules.default.ReceiverSeparationY,
        'ReceiverWaveSuppression': rules.default.ReceiverWaveSuppression,
        'ReceiverBeamAnglesAngle': rules.default.ReceiverBeamAnglesAngle,
        'ReceiverBeamAnglesSkewAngle': rules.default.ReceiverBeamAnglesSkewAngle,
        'ReceiverWedgeLongitudinalWavespeed': rules.default.ReceiverWedgeLongitudinalWavespeed,
        'ReceiverWedgeTransversalWavespeed': rules.default.ReceiverWedgeTransversalWavespeed,
        'ReceiverWedgeDensity': rules.default.ReceiverWedgeDensity,
        'ReceiverWedgeAngle': rules.default.ReceiverWedgeAngle,
        'ReceiverWedgeWidth': rules.default.ReceiverWedgeWidth,
        'ReceiverEulerAnglesPhi': rules.default.ReceiverEulerAnglesPhi,
        'ReceiverEulerAnglesTheta': rules.default.ReceiverEulerAnglesTheta,
        'ReceiverEulerAnglesPsi': rules.default.ReceiverEulerAnglesPsi,
        'ReceiverCouplant': rules.default.ReceiverCouplant,
        'ReceiverDistanceProbeSurface': rules.default.ReceiverDistanceProbeSurface,
        'ReceiverFocusDepth': rules.default.ReceiverFocusDepth,
        'DefectPositionX': rules.default.DefectPositionX,
        'DefectPositionY': rules.default.DefectPositionY,
        'DefectSpecificationVariant': rules.default.DefectSpecificationVariant,
        'DefectSpecificationMeasurementDiameter': rules.default.DefectSpecificationMeasurementDiameter,
        'DefectSpecificationMeasurementCentreDepth': rules.default.DefectSpecificationMeasurementCentreDepth,
        'DefectSpecificationMeasurementDiameterParallel': rules.default.DefectSpecificationMeasurementDiameterParallel,
        'DefectSpecificationMeasurementDiameterPerpendicular': rules.default.DefectSpecificationMeasurementDiameterPerpendicular,
        'DefectSpecificationMeasurementHeight': rules.default.DefectSpecificationMeasurementHeight,
        'DefectSpecificationMeasurementLength': rules.default.DefectSpecificationMeasurementLength,
        'DefectSpecificationMeasurementLengthParallel': rules.default.DefectSpecificationMeasurementLengthParallel,
        'DefectSpecificationAnglesTilt': rules.default.DefectSpecificationAnglesTilt,
        'DefectSpecificationAnglesSkew': rules.default.DefectSpecificationAnglesSkew,
        'DefectSpecificationAnglesTiltCrack': rules.default.DefectSpecificationAnglesTiltCrack,
        'DefectSpecificationInclusionPropertiesRelativeDensity': rules.default.DefectSpecificationInclusionPropertiesRelativeDensity,
        'DefectSpecificationInclusionPropertiesLongitudinalWavespeed': rules.default.DefectSpecificationInclusionPropertiesLongitudinalWavespeed,
        'DefectSpecificationInclusionPropertiesTransversalWavespeed': rules.default.DefectSpecificationInclusionPropertiesTransversalWavespeed,
        'DefectSpecificationInclusionPropertiesDamping': rules.default.DefectSpecificationInclusionPropertiesDamping,
        'DefectSpecificationCircularPropertiesVariant': rules.default.DefectSpecificationCircularPropertiesVariant,
        'DefectSpecificationCircularPropertiesStressQuotient': rules.default.DefectSpecificationCircularPropertiesStressQuotient,
        'DefectSpecificationCircularPropertiesContactDiameter': rules.default.DefectSpecificationCircularPropertiesContactDiameter,
        'DefectSurfacesBackwallEnabled': rules.default.DefectSurfacesBackwallEnabled,
        'DefectSurfacesBackwallDepth': rules.default.DefectSurfacesBackwallDepth,
        'DefectSurfacesBackwallTiltHorizontal': rules.default.DefectSurfacesBackwallTiltHorizontal,
        'DefectSurfacesRoughnessEnabled': rules.default.DefectSurfacesRoughnessEnabled,
        'DefectSurfacesRoughnessRMSHeight': rules.default.DefectSurfacesRoughnessRMSHeight,
        'DefectSurfacesRoughnessCorrelationLength': rules.default.DefectSurfacesRoughnessCorrelationLength,
        'DefectSurfacesIntegration': rules.default.DefectSurfacesIntegration,
    };

    constructor() {
        
    }

    Validate(treePath: string, value: string | number | boolean): IValidationResult {
        if (treePath in this.rules === false) {
            return { isValid: true, isDisabled: false, message: 'Value could not be validated' };
        }

        return this.rules[treePath](value);
    }
}