name: CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 
      - name: Install prereqs
        uses: actions/setup-node@v3
      - name: Run install
        run: |
          npm install yarn
          yarn install
          yarn build
      - name: Compress dist
        run: |
          tar -zcvf dist.tar.gz dist/ 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-artifact
          path: |
            dist.tar.gz
