name: Dev

on: 
  push:
    branches:
      - 'releases/**'
      - 'feature/**'
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 
      - name: Extract tauri config
        run: |
          chcp 65001 #set code page to utf-8
          echo 'PACKAGE_JSON<<EOF' >> $env:GITHUB_ENV
          cat ./src-tauri/tauri.conf.json >> $env:GITHUB_ENV
          echo 'EOF' >> $env:GITHUB_ENV
          echo $env:GITHUB_ENV
      - name: Extract package info from Tauri Config
        run: |
          echo 'PACKAGE_VERSION=${{ fromJson(env.PACKAGE_JSON).package.version }}' >> $env:GITHUB_ENV
          echo 'PRODUCT_NAME=${{ fromJson(env.PACKAGE_JSON).package.productName }}' >> $env:GITHUB_ENV
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install tauri-cli
        run: |
          cargo install tauri-cli
      - name: Run install
        run: |
          npm install yarn
          cargo tauri build
      - name: Compress dist
        run: |
          tar -zcvf ${{ env.PRODUCT_NAME }}_${{ env.PACKAGE_VERSION }}.tar.gz src-tauri/target/release
          cp ./src-tauri/target/release/bundle/msi/${{ env.PRODUCT_NAME }}_${{ env.PACKAGE_VERSION }}_x64_en-US.msi ./${{ env.PRODUCT_NAME }}_${{ env.PACKAGE_VERSION }}_x64_en-US.msi
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PRODUCT_NAME }}_${{ env.PACKAGE_VERSION }}_dev
          path: |
            ${{ env.PRODUCT_NAME }}_${{ env.PACKAGE_VERSION }}.tar.gz
            ${{ env.PRODUCT_NAME }}_${{ env.PACKAGE_VERSION }}_x64_en-US.msi