name: Release

on: 
  push:
    tags:
      - "*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 
      - name: Extract tauri config
        run: |
          echo $(jq --arg version "${{ github.ref_name }}" '.version = ($version)' ./src-tauri/tauri.conf.json) > ./src-tauri/tauri.conf.json
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install tauri-cli
        run: |
          cargo install tauri-cli
      - name: Run install
        run: |
          npm install yarn
          cargo tauri build
      - name: Compress dist
        run: |
          tar -zcvf SimSUNDT_${{ github.ref_name }}.tar.gz src-tauri/target/release
          cp ./src-tauri/target/release/bundle/msi/SimSUNDT_${{ github.ref_name }}_x64_en-US.msi ./SimSUNDT_${{ github.ref_name }}_x64_en-US.msi
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SimSUNDT_${{ github.ref_name }}_release
          path: |
            SimSUNDT_${{ github.ref_name }}.tar.gz
            SimSUNDT_${{ github.ref_name }}_x64_en-US.msi
  publish:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: SimSUNDT_${{ github.ref_name }}_release
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            SimSUNDT_${{ github.ref_name }}_x64_en-US.msi
